### ISSUE TITLE
Refinamento de Requisitos Funcionais

### ISSUE THREAD

**Issue by algorithmadrock** [Maicaoxd/ReclameGeral#11]
RF01 CHECK - Registro de reclamações:
O sistema deve permitir o registro de reclamações de qualquer natureza.
As reclamações podem incluir texto, anexos de documentos, e imagens para suporte.
O sistema deve permitir anexar imagens ou documentos que comprovem o vínculo do reclamante com a empresa.
Os dados anexados devem ser armazenados de acordo com as normas da LGPD.

RF02 CHECK- Cadastro prévio da empresa a ser reclamada:
O sistema deve permitir que o reclamante cadastre a empresa com CNPJ ou Nome Fantasia ao registrar a reclamação.
Deve validar a existência do CNPJ no momento do cadastro. 
  -- Apenas validação de CPNJ, empresas podem ter cnpj inativos

RF03 CHECK - Critérios de avaliação de reclamações:
O sistema deve permitir avaliações de 0.0 a 10.0 tanto para a empresa quanto para a reclamação.
A avaliação da empresa deve ser exibida após um mínimo de 10 reclamações.
-- Feedback geral pós atedimento (Voltaria a comprar, "seu problema foi resolvido?", motivo da nota e nota)

RF04 CHECK- Cadastro de pessoas jurídicas:
O sistema deve permitir que empresas se cadastrem diretamente.
O cadastro deve incluir informações como CNPJ, Razão Social, e Nome Fantasia.

RF05 CHECK- Armazenamento de histórico de reclamações:
O sistema deve armazenar todas as reclamações e suas respectivas respostas.
Deve ser possível consultar o histórico por usuário e por empresa.
-- Para onde vão reclamações de contas deletadas? (LGPD)
-- Após encerradas (avaliadas pelo usuário) as reclamações são desvinculadas do usuário autor para ser persistida na base

RF06 CHECK - Critérios para fechar uma reclamação:
A reclamação pode ser marcada como resolvida somente após a confirmação do reclamante.
Se não houver resposta dentro de um período determinado, o reclamante pode encerrar a reclamação e registrar uma avaliação.
-- Prazo de resposta 5 dias úteis/7 dias corridos

RF07  CHECK- Critérios para tratativa de reclamantes Spam:
O sistema deve manter uma blacklist de clientes que fazem reclamações abusivas ou infundadas.
Critérios para inclusão na blacklist devem ser definidos (ex.: número de reclamações infundadas).
-- Reclamações terão um intervalo de tempo para serem feitas.
-- Blocklist feita para cada empresa individualmente?
-- O que um usuário no spam sofre como penalidade?

RF08 CHECK - Tratativa de match da reclamação com o perfil da empresa indicada:
O sistema deve direcionar a reclamação para a empresa correta com base no CNPJ fornecido.

RF09 CHECK - Exportação de histórico de reclamações:
O sistema deve permitir a exportação do histórico de reclamações em formato PDF ou CSV.
-- Ambos os usuários podem exportar reclamações

RF11 CHECK - Sugestão de possíveis órgãos públicos responsáveis:
O sistema deve sugerir respostas automáticas para as empresas com base na categoria da reclamação.
Deve indicar ao reclamante o órgão público responsável pela queixa.

**Comment by Stefannysoares** [comment]
**Sugestão de possiveis categorias e orgãos responsáveis com base na categoria, RF11 - Sugestão de possíveis órgãos públicos responsáveis, podemos definir melhor os nomes das categorias**

> **RF11 - Sugestão de possíveis órgãos públicos responsáveis:** O sistema deve sugerir respostas automáticas para as empresas com base na categoria da reclamação. Deve indicar ao reclamante o órgão público responsável pela queixa.
>
>  Os consumidores possuem direito de fazer diversos tipos de reclamações relacionadas a produtos e serviços. As principais categorias de reclamações incluem:
> 
> **Produtos com Defeito**: Reclamações sobre produtos que apresentem defeitos de fabricação, defeitos ocultos ou que não funcionem conforme o esperado. 
> 
> **Serviços Mal Prestados:** Reclamações sobre serviços que não foram executados conforme o contratado ou que apresentem falhas.
> 
> **Publicidade Enganosa:** Reclamações sobre propagandas que induzam o consumidor ao erro, apresentando informações falsas ou incompletas.
> 
> **Cobranças Indevidas:** Reclamações sobre cobranças que o consumidor não reconhece ou considera injustas.
> 
> **Garantias e Assistência Técnica:** Reclamações sobre descumprimento de garantias, sejam elas legais ou contratuais, e problemas com assistência técnica.
> 
> **Práticas Abusivas:** Reclamações sobre práticas comerciais que violem os direitos dos consumidores, como vendas casadas ou cláusulas abusivas em contratos.
> 
> **Atrasos na Entrega**: Reclamações sobre o não cumprimento do prazo de entrega de produtos ou serviços.
> 
> **Produtos e Serviços Não Solicitados:** Reclamações sobre o envio ou a cobrança de produtos e serviços que o consumidor não solicitou.
> 
> **### Órgãos Responsáveis por Atuar nas Reclamações**
> **PROCON (Programa de Proteção e Defesa do Consumidor):** Órgão estadual ou municipal responsável pela proteção dos direitos dos consumidores. Atua na mediação de conflitos entre consumidores e fornecedores, e pode aplicar sanções às empresas.(https://www.procon.sp.gov.br/)
> 
> **ANATEL (Agência Nacional de Telecomunicações):** Responsável por regular e fiscalizar os serviços de telecomunicações no Brasil. Atua em reclamações relacionadas a telefonia, internet e TV por assinatura.(https://www.gov.br/anatel/pt-br/consumidor/quer-reclamar/reclamacao)
> 
> **ANEEL (Agência Nacional de Energia Elétrica):** Responsável por regular e fiscalizar os serviços de energia elétrica no Brasil. Atua em reclamações relacionadas ao fornecimento de energia. (https://www.gov.br/aneel/pt-br/canais_atendimento/reclame-da-distribuidora)
> 
> **ANS (Agência Nacional de Saúde Suplementar):** Responsável por regular e fiscalizar os planos de saúde no Brasil. Atua em reclamações relacionadas a planos de saúde e atendimento médico.(https://www.ans.gov.br/nip_solicitante/)
> 
> **ANVISA (Agência Nacional de Vigilância Sanitária):** Responsável por regular e fiscalizar produtos e serviços que envolvam saúde, como medicamentos, alimentos, e cosméticos. Atua em reclamações relacionadas a esses produtos e serviços.(https://www.gov.br/anvisa/pt-br/canais_atendimento/ouvidoria/orientacoes)
> 
> **BACEN (Banco Central do Brasil):** Responsável pela fiscalização do sistema financeiro nacional. Atua em reclamações relacionadas a bancos e instituições financeiras. (https://www.bcb.gov.br/meubc/registrar_reclamacao)
> 
> **INMETRO (Instituto Nacional de Metrologia, Qualidade e Tecnologia):** Responsável por assegurar a conformidade de produtos e serviços com padrões de qualidade e segurança. Atua em reclamações relacionadas à qualidade e segurança de produtos. (https://www.gov.br/inmetro/pt-br/canais_atendimento/ouvidoria/faca-sua-manifestacao)
> 
> **DECON (Delegacia de Defesa do Consumidor):** Órgão da polícia civil que atua em investigações e repressão a crimes contra o consumidor. (Unidades Físicas ou https://www.decon.com.br/contato.htm)
> 
> **Juizados Especiais Cíveis:** Tribunais que julgam causas de menor complexidade, incluindo muitas questões de consumo, de forma mais rápida e simplificada.
>
> 
> **Exemplos de Juizados Especiais:**
> Juizado Especial de Relações de Consumo: Trata especificamente de causas relacionadas ao direito do consumidor.
> Juizado Especial de Trânsito: Trata de causas relacionadas a acidentes de trânsito.
> Juizado Especial de Pequenas Causas: Abrange diversas áreas de menor complexidade, como cobranças, disputas contratuais, e questões de vizinhança.
> Os Juizados Especiais Cíveis são uma importante ferramenta para a democratização do acesso à justiça, permitindo que questões menores sejam resolvidas de forma mais rápida e menos burocrática.

**Comment by algorithmadrock** [comment]
Justificativas para as Adições
RF12 - Notificações:
Manter os usuários informados sobre o status das reclamações aumenta a transparência e engajamento com a plataforma.

RF13 - Filtragem e Pesquisa de Reclamações:
Facilita a navegação e gestão das reclamações, permitindo que usuários encontrem rapidamente informações específicas.

RF14 - Feedback do Usuário:
Permitir feedback ajuda a identificar problemas e oportunidades de melhoria na plataforma.

RF15 - Moderação de Conteúdo:
Garante que o conteúdo na plataforma seja apropriado e útil, mantendo um ambiente respeitoso e produtivo.

RF16 - Relatórios e Estatísticas:
Fornece insights valiosos para empresas e administradores sobre o desempenho e padrões de reclamações.

RNF07 - Escalabilidade:
Assegura que o sistema possa crescer sem comprometer a performance à medida que mais usuários aderem.

RNF08 - Segurança:
Protege os dados dos usuários e a integridade do sistema contra ameaças.

RNF09 - Desempenho:
Melhor experiência do usuário com respostas rápidas e eficientes.

RNF10 - Acessibilidade:
Garante que o sistema seja utilizável por todos, independentemente de habilidades físicas.

RNF11 - Backup e Recuperação:
Minimiza a perda de dados e garante a continuidade do serviço em caso de problemas técnicos.
