### ISSUE TITLE
Perfilamento

### ISSUE THREAD

**Issue by algorithmadrock** [Maicaoxd/ReclameGeral#3]
- Mapear quantos perfis existem e suas necessidades
- Segmentar telas do protótipo

**Comment by Stefannysoares** [comment]
Esboço de uma possibilidade de segregação de perfis de acesso por funcionalidades. 

![Image](https://github.com/Maicaoxd/ReclameGeral/assets/94409895/698f3bd1-0cf8-43c8-a887-3ce0e15ff0af)

**Comment by Stefannysoares** [comment]
Criação de perfis de usuário que agrupam um conjunto de permissões e funções baseadas nas necessidades específicas de diferentes tipos de usuários.

**Esboço de uma idealização com base no briefing do projeto. (Utilizado IA)**

Para o sistema do projeto "Reclame Geral", o perfilamento dos usuários pode ser feito com base nas diferentes funções e responsabilidades associadas a cada tipo de usuário. Aqui está uma sugestão de perfis de usuário e suas respectivas permissões:

### Perfis de Usuário

1. **Administrador**
   - Gerenciar usuários (criar, editar, remover)
   - Gerenciar empresas (aprovar ou remover cadastro)
   - Acessar e exportar histórico de reclamações
   - Acessar blacklist de clientes problemáticos
   - Gerenciar critérios de avaliação
   - Visualizar todas as reclamações e suas resoluções
   - Acessar logs e auditoria do sistema
   - Configurar sugestões de respostas para reclamações

2. **Reclamante** (Pessoa Física)
   - Registrar reclamações
   - Anexar documentos de comprovação de vínculo com a empresa
   - Avaliar empresas e reclamações
   - Consultar histórico de suas reclamações
   - Marcar reclamações como resolvidas
   - Exportar histórico de suas reclamações
   - Receber sugestões de órgãos públicos responsáveis

3. **Representante de Empresa** (Pessoa Jurídica)
   - Cadastrar a empresa
   - Acessar e responder reclamações direcionadas à empresa
   - Marcar reclamações como resolvidas (após confirmação do reclamante)
   - Visualizar avaliações e histórico de reclamações da empresa
   - Gerenciar perfil da empresa

4. **Moderador**
   - Revisar e aprovar cadastros de empresas
   - Monitorar e gerenciar blacklist de clientes problemáticos
   - Avaliar reclamações marcadas como SPAM
   - Ajudar na resolução de disputas entre reclamantes e empresas
   - Acessar logs e auditoria do sistema
   - Gerenciar sugestões de respostas para reclamações

### Permissões de Acesso

#### Administrador
- **Registro de reclamações**: Visualizar todas
- **Cadastro de empresas**: Aprovar, editar, remover
- **Avaliação de empresas e reclamações**: Gerenciar critérios e visualizar avaliações
- **Histórico de reclamações**: Acessar e exportar
- **Marcação de reclamações como resolvidas**: Visualizar e gerenciar
- **Blacklist de clientes problemáticos**: Acessar e gerenciar
- **Exportação de histórico de reclamações**: Acessar e exportar
- **Anexos de documentos**: Visualizar todos
- **Sugestões de respostas**: Configurar e gerenciar

#### Reclamante - Pessoa Física
- **Registro de reclamações**: Criar
- **Cadastro de empresas**: Visualizar e selecionar no momento da reclamação
- **Avaliação de empresas e reclamações**: Avaliar
- **Histórico de reclamações**: Consultar e exportar suas próprias
- **Marcação de reclamações como resolvidas**: Marcar suas próprias
- **Blacklist de clientes problemáticos**: N/A
- **Exportação de histórico de reclamações**: Exportar suas próprias
- **Anexos de documentos**: Anexar e visualizar suas próprias
- **Sugestões de respostas**: Receber

#### Representante de Empresa - Pessoa Jurídica
- **Registro de reclamações**: Visualizar direcionadas à sua empresa
- **Cadastro de empresas**: Criar e gerenciar perfil da empresa
- **Avaliação de empresas e reclamações**: Visualizar avaliações da empresa
- **Histórico de reclamações**: Consultar reclamações da empresa
- **Marcação de reclamações como resolvidas**: Marcar resolvidas (após confirmação)
- **Blacklist de clientes problemáticos**: N/A
- **Exportação de histórico de reclamações**: N/A
- **Anexos de documentos**: Visualizar anexos relacionados à sua empresa
- **Sugestões de respostas**: Receber

#### Moderador
- **Registro de reclamações**: Visualizar todas
- **Cadastro de empresas**: Revisar e aprovar
- **Avaliação de empresas e reclamações**: Monitorar
- **Histórico de reclamações**: Visualizar
- **Marcação de reclamações como resolvidas**: Monitorar
- **Blacklist de clientes problemáticos**: Gerenciar
- **Exportação de histórico de reclamações**: N/A
- **Anexos de documentos**: Visualizar todos
- **Sugestões de respostas**: Gerenciar

### Segregação de Acessos
A segregação de acessos deve garantir que diferentes perfis tenham permissões específicas, minimizando riscos e garantindo segurança e conformidade:

- **Registro de reclamações**: Somente reclamantes.
- **Cadastro de empresas**: Somente representantes de empresas e administradores (para aprovação).
- **Avaliação de empresas e reclamações**: Somente reclamantes (para avaliação), administradores e moderadores (para monitoramento).
- **Histórico de reclamações**: Reclamantes (suas próprias), representantes de empresas (as da empresa), administradores e moderadores (todas).
- **Marcação de reclamações como resolvidas**: Reclamantes (suas próprias), representantes de empresas (somente com confirmação).
- **Blacklist de clientes problemáticos**: Moderadores e administradores.
- **Exportação de histórico de reclamações**: Reclamantes (suas próprias), administradores (todas).
- **Anexos de documentos**: Reclamantes (suas próprias), representantes de empresas (relacionados à empresa), administradores e moderadores (todos).
- **Sugestões de respostas**: Reclamantes (receber), administradores e moderadores (configurar).

Essa estrutura de perfilamento e segregação de acessos ajuda a manter o sistema organizado, seguro e eficiente, garantindo que os usuários possam executar suas funções sem comprometer a integridade e a segurança dos dados.

**Comment by algorithmadrock** [comment]
- Os perfis principais são: Administrador, Empresa e Usuário. 
- Moderadores e administrador não podem ser cadastrados e possuem uma página de login segregada
- Moderadores são criados por administradores apenas
