### ISSUE TITLE
Web - Revisar Protótipos

### ISSUE THREAD

**Issue by Maicaoxd** [Maicaoxd/ReclameGeral#4]
Revisar protótipos desenvolvidos até o momento.
Depende do Perfilamento e do Refinamento de Requisitos

**Comment by Stefannysoares** [comment]
Segue um primeiro refinamentos dos requisitos do projeto, para avaliarmos e validarmos em conjunto. Com base na decisão final, refinaremos os protótipos de telas, ja aplicando as questões de perfilamento.

**Refinamento dos Requisitos Funcionais**

**RF01 - Registro de reclamações:**
O sistema deve permitir o registro de reclamações de qualquer natureza.
As reclamações podem incluir texto, anexos de documentos, e imagens para suporte.

**RF02 - Cadastro prévio da empresa a ser reclamada:**
O sistema deve permitir que o reclamante cadastre a empresa com CNPJ ou Nome Fantasia ao registrar a reclamação.
Deve validar a existência do CNPJ no momento do cadastro.

**RF03 - Critérios de avaliação de reclamações:**
O sistema deve permitir avaliações de 0.0 a 10.0 tanto para a empresa quanto para a reclamação.
A avaliação da empresa deve ser exibida após um mínimo de 10 reclamações.

**RF04 - Cadastro de pessoas jurídicas:**
O sistema deve permitir que empresas se cadastrem diretamente.
O cadastro deve incluir informações como CNPJ, Razão Social, e Nome Fantasia.

**RF05 - Armazenamento de histórico de reclamações:**
O sistema deve armazenar todas as reclamações e suas respectivas respostas.
Deve ser possível consultar o histórico por usuário e por empresa.

**RF06 - Critérios para fechar uma reclamação:**
A reclamação pode ser marcada como resolvida somente após a confirmação do reclamante.
Se não houver resposta dentro de um período determinado, o reclamante pode encerrar a reclamação e registrar uma avaliação.

**RF07 - Critérios para tratativa de reclamantes Spam:**
O sistema deve manter uma blacklist de clientes que fazem reclamações abusivas ou infundadas.
Critérios para inclusão na blacklist devem ser definidos (ex.: número de reclamações infundadas).

**RF08 - Tratativa de match da reclamação com o perfil da empresa indicada:**
O sistema deve direcionar a reclamação para a empresa correta com base no CNPJ fornecido.

**RF09 - Exportação de histórico de reclamações:**
O sistema deve permitir a exportação do histórico de reclamações em formato PDF ou CSV.

**RF10 - Comprovação de vínculo do reclamante com a empresa indicada:**
O sistema deve permitir anexar imagens ou documentos que comprovem o vínculo do reclamante com a empresa.
Os dados anexados devem ser armazenados de acordo com as normas da LGPD.

**RF11 - Sugestão de possíveis órgãos públicos responsáveis:**
O sistema deve sugerir respostas automáticas para as empresas com base na categoria da reclamação.
Deve indicar ao reclamante o órgão público responsável pela queixa.

**Refinamento dos Requisitos Não Funcionais**
**RNF01 - Multiplataforma:**
O sistema deve ser acessível via web e aplicativos móveis (iOS e Android).

**RNF02 - Banco de dados:**
O banco de dados utilizado será MySQL.

**RNF03 - Verificação e Validação de identidade:**
O sistema deve validar CPF e CNPJ no ato do cadastro do usuário e empresa.

**RNF04 - Tecnologias utilizadas para desenvolvimento:**
O sistema será desenvolvido em Flutter e Node.js com o framework Feathers.

**RNF05 - SSO:**
O sistema deve suportar login via contas Google e Apple.

**RNF06 - Relacionamento reclamante-reclamação:**
Somente usuários cadastrados podem registrar reclamações.

**Possíveis Requisitos Adicionais**
**Requisitos Funcionais Adicionais**

Esses requisitos adicionais seriam para cobrir uma lacuna na modelagem, deixar claro que esses aspectos foram pensados mas na minha visão não necessáriamente precisa ser implementado em projeto.

**RF12 - Notificações:**
O sistema deve enviar notificações aos usuários (tanto reclamantes quanto empresas) sobre o status das reclamações.
As notificações podem ser via email, push notifications (no app) e SMS.

**RF13 - Filtragem e Pesquisa de Reclamações:**
O sistema deve permitir a filtragem e pesquisa de reclamações por diversos critérios, como data, status, empresa, e tipo de problema.

**RF14 - Feedback do Usuário:**
O sistema deve permitir que os usuários forneçam feedback sobre a plataforma, sugerindo melhorias ou reportando problemas.

**RF15 - Moderação de Conteúdo:**
O sistema deve possuir um mecanismo para a moderação de conteúdo ofensivo ou inadequado nas reclamações e respostas.
O conteúdo pode ser moderado automaticamente (ex.: por palavras-chave) ou manualmente por administradores.

**RF16 - Relatórios e Estatísticas:**
O sistema deve fornecer relatórios e estatísticas detalhadas sobre as reclamações, incluindo gráficos de desempenho das empresas, tipos de reclamações mais comuns, e tempo médio de resolução.

**Requisitos Não Funcionais Adicionais**

**RNF07 - Escalabilidade:** (é só uma ideia, não precisa ser um entregável no projeto)
O sistema deve ser escalável para suportar um grande número de usuários e reclamações simultaneamente.

**RNF08 - Segurança:** (é só uma ideia, não precisa ser um entregável no projeto)
O sistema deve implementar boas práticas de segurança, como criptografia de dados sensíveis, autenticação de dois fatores (2FA), e proteção contra ataques comuns (ex.: SQL Injection, Cross-Site Scripting).

**RNF09 - Desempenho:** (é só uma ideia, não precisa ser um entregável no projeto)
O sistema deve ter tempos de resposta rápidos, com latência mínima para operações comuns.

**RNF10 - Acessibilidade:** (é só uma ideia, não precisa ser um entregável no projeto)
O sistema deve ser acessível para pessoas com deficiência, seguindo as diretrizes de acessibilidade (WCAG).

**RNF11 - Backup e Recuperação:** (é só uma ideia, não precisa ser um entregável no projeto)
O sistema deve ter um plano de backup regular e procedimentos de recuperação de dados em caso de falhas.

**Justificativas para as Adições**
**RF12 - Notificações:**
Manter os usuários informados sobre o status das reclamações aumenta a transparência e engajamento com a plataforma.

**RF13 - Filtragem e Pesquisa de Reclamações:**
Facilita a navegação e gestão das reclamações, permitindo que usuários encontrem rapidamente informações específicas.

**RF14 - Feedback do Usuário:**
Permitir feedback ajuda a identificar problemas e oportunidades de melhoria na plataforma.

**RF15 - Moderação de Conteúdo:**
Garante que o conteúdo na plataforma seja apropriado e útil, mantendo um ambiente respeitoso e produtivo.

**RF16 - Relatórios e Estatísticas:**
Fornece insights valiosos para empresas e administradores sobre o desempenho e padrões de reclamações.

**RNF07 - Escalabilidade:**
Assegura que o sistema possa crescer sem comprometer a performance à medida que mais usuários aderem.

**RNF08 - Segurança:**
Protege os dados dos usuários e a integridade do sistema contra ameaças.

**RNF09 - Desempenho:**
Melhor experiência do usuário com respostas rápidas e eficientes.

**RNF10 - Acessibilidade:**
Garante que o sistema seja utilizável por todos, independentemente de habilidades físicas.

**RNF11 - Backup e Recuperação:**
Minimiza a perda de dados e garante a continuidade do serviço em caso de problemas técnicos.

**Comment by algorithmadrock** [comment]
Aguardamos parecer do Joilson, foi revisado pela equipe de devs apenas
